version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: some-clickhouse-server
    ports:
      - 18123:8123
      - 29000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./ch_data:/var/lib/clickhouse
      - ./ch_logs:/var/log/clickhouse-server
    networks:
      - clickhouse-network
    restart: always
networks:
  clickhouse-network:
    driver: bridge